DROP TABLE BOARD;
CREATE TABLE BOARD (
	IDX NUMBER PRIMARY KEY,
	WRITER VARCHAR2(20) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(2000),
	CREATED DATE
);

DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;